import {
  BusinessSummary,
  HelperAssignment,
  LoadPlanItem,
  Product,
  ReconciliationItem,
  ShortageAllocation,
  Store,
  StoreRequest,
} from "./types";

export const products: Product[] = [
  { id: "p1", name: "Oatmeal Creme Pies", truckInventory: 6, storageInventory: 12 },
  { id: "p2", name: "Swiss Rolls", truckInventory: 4, storageInventory: 0 },
  { id: "p3", name: "Nutty Buddy", truckInventory: 14, storageInventory: 3 },
  { id: "p4", name: "Honey Buns", truckInventory: 10, storageInventory: 5 },
  { id: "p5", name: "Star Crunch", truckInventory: 8, storageInventory: 6 },
  { id: "p6", name: "Christmas Tree Cakes", seasonal: true, truckInventory: 5, storageInventory: 2 },
];

export const stores: Store[] = [
  {
    id: "s1",
    stopNumber: 1,
    name: "Walmart",
    city: "Norwalk",
    priority: "high",
    status: "needs-attention",
    time: "8:15 AM",
    distanceMinutes: 8,
    receivingHours: "7:00 AM – 1:00 PM",
    estServiceTimeMinutes: 45,
    lastDeliveryCases: 42,
    recentSalesTrend: "up 18%",
    suggestedOrderCases: 51,
    suggestedOrderConfidence: "high",
    suggestedOrderReasons: [
      "Sales up 18%",
      "Distributor increased this order last 3 Mondays",
      "Promotion this week",
    ],
    approvedOrderCases: null,
    rememberAdjustment: false,
    orderedCases: 51,
    pickedCases: 0,
    deliveredCases: 0,
    stalesCases: 0,
    staleRiskCases: 0,
    promotion: "Endcap display through Sunday",
    specialRequestIds: [],
    contact: { managerName: "Denise Carter", phone: "(419) 555-0142" },
    notes: [
      { id: "n1", text: "Receiving closes at 1:00 PM sharp" },
      { id: "n2", text: "Display approved through Friday" },
    ],
    workflowStep: "order-scan",
  },
  {
    id: "s2",
    stopNumber: 2,
    name: "Convenience Mart",
    city: "Milan",
    priority: "medium",
    status: "needs-attention",
    time: "9:05 AM",
    distanceMinutes: 14,
    receivingHours: "8:00 AM – 5:00 PM",
    estServiceTimeMinutes: 20,
    lastDeliveryCases: 22,
    recentSalesTrend: "flat",
    suggestedOrderCases: 15,
    suggestedOrderConfidence: "medium",
    suggestedOrderReasons: ["Shelf and backstock running high the last two visits", "Lower priority store"],
    approvedOrderCases: null,
    rememberAdjustment: false,
    orderedCases: 15,
    pickedCases: 0,
    deliveredCases: 0,
    stalesCases: 0,
    staleRiskCases: 8,
    staleRiskNote: "8 cases of Nutty Buddy may become stale soon — Walmart sells this faster",
    specialRequestIds: [],
    contact: { managerName: "Ray Holt", phone: "(419) 555-0198" },
    notes: [{ id: "n1", text: "Do not over-order Swiss Rolls at this store" }],
    workflowStep: "order-scan",
  },
  {
    id: "s3",
    stopNumber: 3,
    name: "Corner Grocery",
    city: "Milan",
    priority: "low",
    status: "upcoming",
    time: "9:40 AM",
    distanceMinutes: 6,
    receivingHours: "8:00 AM – 6:00 PM",
    estServiceTimeMinutes: 15,
    lastDeliveryCases: 24,
    recentSalesTrend: "flat",
    suggestedOrderCases: 24,
    suggestedOrderConfidence: "high",
    suggestedOrderReasons: ["Sales have been steady with no significant change"],
    approvedOrderCases: null,
    rememberAdjustment: false,
    orderedCases: 24,
    pickedCases: 0,
    deliveredCases: 0,
    stalesCases: 0,
    staleRiskCases: 0,
    specialRequestIds: [],
    contact: { managerName: "Alicia Munoz", phone: "(419) 555-0110" },
    notes: [],
    workflowStep: "order-scan",
  },
  {
    id: "s4",
    stopNumber: 4,
    name: "Quick Stop",
    city: "Willard",
    priority: "medium",
    status: "needs-attention",
    time: "10:10 AM",
    distanceMinutes: 12,
    receivingHours: "6:00 AM – 2:00 PM",
    estServiceTimeMinutes: 15,
    lastDeliveryCases: 12,
    recentSalesTrend: "flat",
    suggestedOrderCases: 10,
    suggestedOrderConfidence: "medium",
    suggestedOrderReasons: ["Last visit had damaged product that still needs documented"],
    approvedOrderCases: null,
    rememberAdjustment: false,
    orderedCases: 10,
    pickedCases: 0,
    deliveredCases: 0,
    stalesCases: 3,
    staleRiskCases: 0,
    specialRequestIds: [],
    contact: { managerName: "Tom Behr", phone: "(419) 555-0166" },
    notes: [{ id: "n1", text: "Manager prefers delivery before 10 AM" }],
    workflowStep: "order-scan",
  },
  {
    id: "s5",
    stopNumber: 5,
    name: "Family Market",
    city: "Willard",
    priority: "medium",
    status: "upcoming",
    time: "10:45 AM",
    distanceMinutes: 5,
    receivingHours: "7:00 AM – 6:00 PM",
    estServiceTimeMinutes: 25,
    lastDeliveryCases: 28,
    recentSalesTrend: "up 6%",
    suggestedOrderCases: 32,
    suggestedOrderConfidence: "high",
    suggestedOrderReasons: ["Sales trending up over the last month"],
    approvedOrderCases: null,
    rememberAdjustment: false,
    orderedCases: 32,
    pickedCases: 0,
    deliveredCases: 0,
    stalesCases: 0,
    staleRiskCases: 0,
    specialRequestIds: [],
    contact: { managerName: "Priya Shah", phone: "(419) 555-0121" },
    notes: [],
    workflowStep: "order-scan",
  },
  {
    id: "s6",
    stopNumber: 6,
    name: "Sunrise Deli",
    city: "Willard",
    priority: "low",
    status: "upcoming",
    time: "11:15 AM",
    distanceMinutes: 4,
    receivingHours: "8:00 AM – 4:00 PM",
    estServiceTimeMinutes: 10,
    lastDeliveryCases: 9,
    recentSalesTrend: "flat",
    suggestedOrderCases: 9,
    suggestedOrderConfidence: "high",
    suggestedOrderReasons: ["Sales have been steady with no significant change"],
    approvedOrderCases: null,
    rememberAdjustment: false,
    orderedCases: 9,
    pickedCases: 0,
    deliveredCases: 0,
    stalesCases: 0,
    staleRiskCases: 0,
    specialRequestIds: [],
    contact: { managerName: "Ben Foley", phone: "(419) 555-0134" },
    notes: [],
    workflowStep: "order-scan",
  },
  {
    id: "s7",
    stopNumber: 7,
    name: "Kroger",
    city: "Norwalk",
    priority: "high",
    status: "upcoming",
    time: "12:05 PM",
    distanceMinutes: 9,
    receivingHours: "6:00 AM – 3:00 PM",
    estServiceTimeMinutes: 40,
    lastDeliveryCases: 50,
    recentSalesTrend: "up 10%",
    suggestedOrderCases: 58,
    suggestedOrderConfidence: "high",
    suggestedOrderReasons: ["Sales up 10%", "Promotion this week"],
    approvedOrderCases: null,
    rememberAdjustment: false,
    orderedCases: 58,
    pickedCases: 0,
    deliveredCases: 0,
    stalesCases: 0,
    staleRiskCases: 0,
    promotion: "Seasonal endcap starting this week",
    specialRequestIds: [],
    contact: { managerName: "Wanda Price", phone: "(419) 555-0177" },
    notes: [{ id: "n1", text: "Receiving closes at 3:00 PM" }],
    workflowStep: "order-scan",
  },
  {
    id: "s8",
    stopNumber: 8,
    name: "Value Foods",
    city: "Bellevue",
    priority: "medium",
    status: "needs-attention",
    time: "12:50 PM",
    distanceMinutes: 18,
    receivingHours: "8:00 AM – 5:00 PM",
    estServiceTimeMinutes: 20,
    lastDeliveryCases: 20,
    recentSalesTrend: "flat",
    suggestedOrderCases: 24,
    suggestedOrderConfidence: "medium",
    suggestedOrderReasons: ["Manager requested extra cases ahead of a weekend promotion"],
    approvedOrderCases: null,
    rememberAdjustment: false,
    orderedCases: 24,
    pickedCases: 0,
    deliveredCases: 0,
    stalesCases: 0,
    staleRiskCases: 0,
    specialRequestIds: [],
    contact: { managerName: "Greg Owens", phone: "(419) 555-0155" },
    notes: [],
    workflowStep: "order-scan",
  },
  {
    id: "s9",
    stopNumber: 9,
    name: "Main Street Pharmacy",
    city: "Bellevue",
    priority: "low",
    status: "upcoming",
    time: "1:30 PM",
    distanceMinutes: 5,
    receivingHours: "9:00 AM – 5:00 PM",
    estServiceTimeMinutes: 10,
    lastDeliveryCases: 6,
    recentSalesTrend: "flat",
    suggestedOrderCases: 6,
    suggestedOrderConfidence: "high",
    suggestedOrderReasons: ["Sales have been steady with no significant change"],
    approvedOrderCases: null,
    rememberAdjustment: false,
    orderedCases: 6,
    pickedCases: 0,
    deliveredCases: 0,
    stalesCases: 0,
    staleRiskCases: 0,
    specialRequestIds: [],
    contact: { managerName: "Nora Kim", phone: "(419) 555-0188" },
    notes: [],
    workflowStep: "order-scan",
  },
  {
    id: "s10",
    stopNumber: 10,
    name: "Gas & Go",
    city: "Bellevue",
    priority: "low",
    status: "upcoming",
    time: "2:00 PM",
    distanceMinutes: 3,
    receivingHours: "24 hours",
    estServiceTimeMinutes: 10,
    lastDeliveryCases: 13,
    recentSalesTrend: "up 4%",
    suggestedOrderCases: 15,
    suggestedOrderConfidence: "medium",
    suggestedOrderReasons: ["Sales trending up slightly over the last month"],
    approvedOrderCases: null,
    rememberAdjustment: false,
    orderedCases: 15,
    pickedCases: 0,
    deliveredCases: 0,
    stalesCases: 0,
    staleRiskCases: 0,
    specialRequestIds: [],
    contact: { managerName: "Sam Duarte", phone: "(419) 555-0163" },
    notes: [],
    workflowStep: "order-scan",
  },
  {
    id: "s11",
    stopNumber: 11,
    name: "Target",
    city: "Norwalk",
    priority: "high",
    status: "upcoming",
    time: "2:45 PM",
    distanceMinutes: 10,
    receivingHours: "7:00 AM – 4:00 PM",
    estServiceTimeMinutes: 35,
    lastDeliveryCases: 36,
    recentSalesTrend: "up 6%",
    suggestedOrderCases: 40,
    suggestedOrderConfidence: "high",
    suggestedOrderReasons: ["Sales trending up over the last month"],
    approvedOrderCases: null,
    rememberAdjustment: false,
    orderedCases: 40,
    pickedCases: 0,
    deliveredCases: 0,
    stalesCases: 0,
    staleRiskCases: 0,
    specialRequestIds: [],
    contact: { managerName: "Elena Cho", phone: "(419) 555-0129" },
    notes: [],
    workflowStep: "order-scan",
  },
  {
    id: "s12",
    stopNumber: 12,
    name: "Harbor Market",
    city: "Ashland",
    priority: "low",
    status: "upcoming",
    time: "3:30 PM",
    distanceMinutes: 22,
    receivingHours: "8:00 AM – 5:00 PM",
    estServiceTimeMinutes: 15,
    lastDeliveryCases: 16,
    recentSalesTrend: "flat",
    suggestedOrderCases: 16,
    suggestedOrderConfidence: "high",
    suggestedOrderReasons: ["Sales have been steady with no significant change"],
    approvedOrderCases: null,
    rememberAdjustment: false,
    orderedCases: 16,
    pickedCases: 0,
    deliveredCases: 0,
    stalesCases: 0,
    staleRiskCases: 0,
    specialRequestIds: [],
    contact: { managerName: "Ivy Larsen", phone: "(419) 555-0141" },
    notes: [],
    workflowStep: "order-scan",
  },
  {
    id: "s13",
    stopNumber: 13,
    name: "Ashland Grocery Co-op",
    city: "Ashland",
    priority: "medium",
    status: "catch-up",
    time: "4:10 PM",
    distanceMinutes: 4,
    receivingHours: "8:00 AM – 6:00 PM",
    estServiceTimeMinutes: 20,
    lastDeliveryCases: 19,
    recentSalesTrend: "up 8%",
    suggestedOrderCases: 23,
    suggestedOrderConfidence: "high",
    suggestedOrderReasons: ["Sales up 8%", "Skipped last scheduled visit — carried over from yesterday"],
    approvedOrderCases: null,
    rememberAdjustment: false,
    orderedCases: 23,
    pickedCases: 0,
    deliveredCases: 0,
    stalesCases: 0,
    staleRiskCases: 0,
    specialRequestIds: [],
    contact: { managerName: "Marcus Reed", phone: "(419) 555-0172" },
    notes: [{ id: "n1", text: "Missed Monday — catch up this visit" }],
    workflowStep: "order-scan",
    isCatchUpFromYesterday: true,
  },
  {
    id: "s14",
    stopNumber: 14,
    name: "Riverside Diner & Market",
    city: "Ashland",
    priority: "low",
    status: "upcoming",
    time: "4:40 PM",
    distanceMinutes: 3,
    receivingHours: "9:00 AM – 3:00 PM",
    estServiceTimeMinutes: 10,
    lastDeliveryCases: 8,
    recentSalesTrend: "flat",
    suggestedOrderCases: 8,
    suggestedOrderConfidence: "high",
    suggestedOrderReasons: ["Sales have been steady with no significant change"],
    approvedOrderCases: null,
    rememberAdjustment: false,
    orderedCases: 8,
    pickedCases: 0,
    deliveredCases: 0,
    stalesCases: 0,
    staleRiskCases: 0,
    specialRequestIds: [],
    contact: { managerName: "Delia Ortiz", phone: "(419) 555-0119" },
    notes: [],
    workflowStep: "order-scan",
  },
];

export const storeRequests: StoreRequest[] = [
  {
    id: "r1",
    storeId: "s10",
    storeName: "Gas & Go — Bellevue",
    productName: "Christmas Tree Cakes",
    quantity: 5,
    neededBy: "Thursday",
    type: "Special Request",
    status: "open",
    createdVia: "voice",
    rawVoiceText: "Sam's Club wants five extra Christmas Tree Cakes Thursday.",
  },
];

export const loadPlan: LoadPlanItem[] = [
  { productId: "p1", productName: "Oatmeal Creme Pies", needed: 24, loaded: 24, order: 1 },
  { productId: "p2", productName: "Swiss Rolls", needed: 18, loaded: 14, order: 2 },
  { productId: "p3", productName: "Nutty Buddy", needed: 20, loaded: 14, order: 3 },
  { productId: "p4", productName: "Honey Buns", needed: 16, loaded: 16, order: 4 },
  { productId: "p6", productName: "Christmas Tree Cakes", needed: 12, loaded: 5, seasonal: true, order: 5 },
];

export const shortageAllocations: ShortageAllocation[] = [
  {
    productId: "p3",
    productName: "Nutty Buddy",
    neededToday: 20,
    available: 14,
    allocations: [
      { storeId: "s1", storeName: "Walmart", quantity: 6, reason: "High volume + shelf currently low" },
      { storeId: "s7", storeName: "Kroger", quantity: 5, reason: "Promotion this week" },
      { storeId: "s8", storeName: "Value Foods", quantity: 3, reason: "Special request pending" },
      { storeId: "s10", storeName: "Gas & Go", quantity: 0, reason: "Lower priority — skip today" },
    ],
  },
];

export const reconciliationItems: ReconciliationItem[] = [
  { productId: "p1", productName: "Oatmeal Creme Pies", location: "Truck", expected: 12, physical: 10 },
  { productId: "p2", productName: "Swiss Rolls", location: "Truck", expected: 6, physical: 6 },
  { productId: "p3", productName: "Nutty Buddy", location: "Truck", expected: 8, physical: 9 },
  { productId: "p1", productName: "Oatmeal Creme Pies", location: "Storage", expected: 12, physical: 12 },
  { productId: "p4", productName: "Honey Buns", location: "Storage", expected: 5, physical: 3 },
];

export const businessSummary: BusinessSummary = {
  routeSales: 4820,
  productCost: 1930,
  staleLoss: 186,
  franchiseFee: 300,
  fuel: 210,
  truckPayment: 260,
  insurance: 95,
  repairs: 40,
  helperCost: 0,
  storageRental: 150,
  taxesOther: 120,
};

export const helperAssignments: HelperAssignment[] = [];

export const routeMeta = {
  estimatedRouteTime: "6h 20m",
  weatherNote: "Rain expected after 2 PM — allow extra time between Bellevue stops",
  tomorrowsEstimatedLoad: 312,
};

